{% set name = "hypre" %}
{% set version = "2.15.1" %}
{% set sha256 = "58d215146e1c7c2c11be4cb1eac0d1663a45584efbe5f603205d8c4766b7579f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/LLNL/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openblas
    - {{ mpi }}
  run:
    - openblas
    - {{ mpi }}

test:
  commands:
    - conda inspect objects  hypre  # [osx]
    - conda inspect linkages hypre  # [not win]
    - test -f $PREFIX/include/HYPRE.h
    - test -f $PREFIX/lib/libHYPRE.dylib  # [osx]
    - test -f $PREFIX/lib/libHYPRE.so     # [linux]

about:
  home: http://www.llnl.gov/casc/hypre/
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYRIGHT
  summary: 'high performance preconditioners for sparse linear systems'
  description: |
    HYPRE is a library of high performance preconditioners and solvers featuring
    multigrid methods for the solution of large, sparse linear systems of equations
    on massively parallel computers.
  dev_url: https://github.com/LLNL/hypre

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
