# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxmpimpich
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxmpiopenmpi
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxmpimpich
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxmpiopenmpi

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Vi/arMNGWSvo3Qqnhh2GthyCNGxJuhGxfHfc6RGI+FsQcXejU71/K+yGtwSmck4I19Oo5NJm1ZbkbB7w7ZHJGLNOvjT1llbl7T/8D9WYDnxv8t4+0arc+Haiq4VO3wDr2geIs/x9RFqCRicnVUvVEfkzimMTlEKFQzQV8tFAdC7N3epD4fgkPFFC9q7QzQNnqn+1yKFOcnmpPFOSLiGRWxLQqiPppVOKT3Qo9gttK/BDC0GimcD6RjsZ9x+1c2oSGkSAbWgUepDDICxKaezeGY3SEIC8cOu/U3Pl7D5KpN7Zm9vFmScFjPfCd0arELshvhKjN5gvEdmYV5YQJ8o02WMJE51NpsIdANHrhYJJUEVNb0i8EjJal6AIzsuupxILKUKESa9laJrvjQsyWzauQU/Of90jL/ZNYBCsjeCaOKAYA8u9rnXiR/zuiHKQGiQeao3aDlweistiQa1wQlqM/WKNh9yJ2IgmFZ2tLtaEw7yt1I65Sd1OzIplAMKmz+uUaPC6Ru4Ak6MiIysbrSlX7ICY0xtmAoOwXlGXj/zon1aRaQKOdRlfJHQAqZQWqSz3F1u50lpCiT7CNLx2+4pd8QvUIcZaLwfQKRMZ4YPyytq7HQj40lna4uThl8i+XWE8PI1wJ7f3qyT3JY9K+bTjPc8BNfPdAZ0Rw4/bNx23f68="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
