travis:
  secure:
    BINSTAR_TOKEN: rC01G6g/EKj/nhZgQw4HNIJjcbF/XK+L2Fq/Yh6kZqbU46nr9y5z+nU+bNZ7BOoMzKKmep9vupWs9gxQbr89UYEl0l2eegx5piPmwV/R3fgYRBPceUz24wmJT5ZlEQtARcioQUltLFQvcHwDB2A1rV0pNmdXuvG+Itz+QJUfMUNq24eOVhDZafBFF4KX3PG3hrxRoGjP7Qll4Vz1PSq4gglYzUEkUYuTmxko216rVj/G4eRovAGfNK+Bo2aJXKDt36ZG0bDJmGPLotEB96Hp+kXf+MlZHNA1SVdc/xHa57K4nKkN7lq7LR2M7HYVoZZQgivsVoplgrx5HPTzEtM5jlbDiI5Mw3A89VYCBQaUQIubvflzafXjcjNPW6NfphHRHiDDvfNABLINLhyuGeadH8W8/rIVHYAkxV2PJWymfPw2rCgcKoT1HoxTB0V6xw7NASlshXeLiX7BVU+hO5opBlJ8C/d90TB/Vv/5D3I5kZKZ7SsZ7H6jB1kmLpqmhaCjU0iupa1Ktnlh3tiUUWk/LBFe2yTH/P5QQTqk91n8jCLtCDlv37iC0SVM9DiLL5vFn9gWEXHgw7XVGIAKWjd7dxZjzJj7Z6V/QCe9d6dhRX6XrWK1nna+hAksMZxqKaVLZ5m84+DYHPrCqaczsapkyNpaoZISZBquHZNIb66U49g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
